services:
  - type: web
    name: psychobot
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && mkdir -p bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp && chmod a+rx bin/yt-dlp"
    startCommand: "node index.js"
